//! [Lucide](https://lucide.dev/icons/) icons as tinted UI nodes.
//!
//! Bevy has no native SVG renderer, so each icon is pre-rasterized to a
//! **white-on-transparent PNG** (`assets/icons/*.png`, regenerated by
//! `just icons` → `cargo xtask icons`). Because the art is white, `ImageNode`'s `color`
//! tint *becomes* the icon's colour — pass a theme token and the icon re-tones
//! with everything else.
//!
//! ```
//! # use bevy::prelude::*;
//! # use arenic_game::icon::{icon, Icon};
//! # fn sys(mut commands: Commands, assets: Res<AssetServer>, c: Color) {
//! let e = icon(&mut commands, &assets, Icon::PanelLeftClose, 18.0, c);
//! # }
//! ```
//!
//! Lucide is ISC licensed; see `assets/icons/LICENSE`.

use bevy::prelude::*;

/// A curated subset of Lucide icons available to the game and storybook. Add a
/// variant here and its name to the `ICONS` list in `xtask`, then `just icons`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Icon {
    PanelLeftClose,
    PanelLeftOpen,
    ChevronRight,
    ChevronDown,
    Folder,
    FolderOpen,
    Palette,
    SwatchBook,
    Type,
    Ruler,
    Box,
    Layers,
    Component,
    User,
    Pyramid,
    Crosshair,
    FlaskConical,
    Donut,
    Hexagon,
    Triangle,
    Music,
    Mountain,
    Gem,
    Sparkles,
    Rotate3d,
}

impl Icon {
    /// The icon's asset path, relative to the `assets/` root.
    pub fn asset_path(self) -> &'static str {
        match self {
            Icon::PanelLeftClose => "icons/panel-left-close.png",
            Icon::PanelLeftOpen => "icons/panel-left-open.png",
            Icon::ChevronRight => "icons/chevron-right.png",
            Icon::ChevronDown => "icons/chevron-down.png",
            Icon::Folder => "icons/folder.png",
            Icon::FolderOpen => "icons/folder-open.png",
            Icon::Palette => "icons/palette.png",
            Icon::SwatchBook => "icons/swatch-book.png",
            Icon::Type => "icons/type.png",
            Icon::Ruler => "icons/ruler.png",
            Icon::Box => "icons/box.png",
            Icon::Layers => "icons/layers.png",
            Icon::Component => "icons/component.png",
            Icon::User => "icons/user.png",
            Icon::Pyramid => "icons/pyramid.png",
            Icon::Crosshair => "icons/crosshair.png",
            Icon::FlaskConical => "icons/flask-conical.png",
            Icon::Donut => "icons/donut.png",
            Icon::Hexagon => "icons/hexagon.png",
            Icon::Triangle => "icons/triangle.png",
            Icon::Music => "icons/music.png",
            Icon::Mountain => "icons/mountain.png",
            Icon::Gem => "icons/gem.png",
            Icon::Sparkles => "icons/sparkles.png",
            Icon::Rotate3d => "icons/rotate-3d.png",
        }
    }

    /// Loads the icon's image handle (cheap; the `AssetServer` dedups by path).
    pub fn handle(self, assets: &AssetServer) -> Handle<Image> {
        assets.load(self.asset_path())
    }
}

/// The `(ImageNode, Node)` bundle for an icon: a `size`×`size` square tinted to
/// `tint`. Use when you want to insert the icon onto an existing entity.
pub fn icon_bundle(assets: &AssetServer, icon: Icon, size: f32, tint: Color) -> impl Bundle {
    (
        ImageNode {
            image: icon.handle(assets),
            color: tint,
            ..default()
        },
        Node {
            width: Val::Px(size),
            height: Val::Px(size),
            flex_shrink: 0.0,
            ..default()
        },
    )
}

/// Spawns a tinted icon and returns its entity.
pub fn icon(commands: &mut Commands, assets: &AssetServer, icon_id: Icon, size: f32, tint: Color) -> Entity {
    commands.spawn(icon_bundle(assets, icon_id, size, tint)).id()
}
