//! RON schemas for the title-screen pipeline.
//!
//! `cargo xtask beats` writes [`Beats`]; `cargo xtask choreograph` reads it and
//! writes [`Choreography`]. The playback side (the `arenic` title scene)
//! deserializes [`Choreography`] with a mirrored schema — the RON file is the
//! contract between the offline generator and the runtime player.

use serde::{Deserialize, Serialize};

/// The title theme's detected tempo + beat grid, in 60 Hz sim ticks.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Beats {
    /// Consensus tempo (beats per minute).
    pub bpm: f64,
    /// Decoded length of the theme, seconds.
    pub duration_secs: f64,
    /// The tick rate the `*_ticks` fields are expressed in (always 60).
    pub ticks_per_second: u32,
    /// Every beat, in ticks, ascending.
    pub beat_ticks: Vec<u32>,
    /// Every 4th beat (the bar / downbeat grid) — where entries cluster.
    pub bar_ticks: Vec<u32>,
}

/// A deterministic title-screen choreography: circles flowing across a grid,
/// each a tick-stamped move script (mirrors the recording grammar — a `start`
/// cell plus unit steps). Generated by `cargo xtask choreograph`; played back
/// by the title scene, which lerps between steps for a smooth glide.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Choreography {
    /// Grid width in cells (x ∈ `0..grid_w`).
    pub grid_w: u32,
    /// Grid height in cells (y ∈ `0..grid_h`).
    pub grid_h: u32,
    /// Total length of the loop in ticks (the theme's duration at 60 Hz).
    pub cycle_ticks: u32,
    /// Every circle's script.
    pub agents: Vec<Agent>,
}

/// One circle: it appears at `spawn_tick` on `start`, applies each step in
/// order, and vanishes at `despawn_tick` (having flowed off an edge).
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Agent {
    /// Tick the circle enters (its `start` cell becomes visible).
    pub spawn_tick: u32,
    /// Tick the circle leaves (it has reached its exit edge).
    pub despawn_tick: u32,
    /// Entry cell `[x, y]`.
    pub start: [i32; 2],
    /// Tick-stamped unit moves, ascending by tick. `dx`/`dy` ∈ {-1, 0, 1} with
    /// at most one nonzero (4-directional), so steps never cross diagonally.
    pub steps: Vec<Step>,
}

/// One unit move completed at `tick`.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Step {
    pub tick: u32,
    pub dx: i32,
    pub dy: i32,
}
